### PR TITLE
added logs support

### PR DESCRIPTION
**Pull request by ravindrasinghh**

### CODE REVIEW

**Comment by tobyclemson** [comment]
Hi @ravindrasinghh,

Thanks for the PR. This doesn't currently have any tests. Are you able to add some? If not, I'll try to find some time later in the week to add some before merging.

Thanks!
Toby

**Comment by ravindrasinghh** [comment]
Hi @tobyclemson ,
Thanks for the reply,I didn't understand the tests here.Can you help me to understand .So I can take care in future before raising any PR.

**Comment by ravindrasinghh** [comment]
@tobyclemson 
Any update on above MR ?

**Comment by tobyclemson** [comment]
@ravindrasinghh [2.1.0-rc.8](https://registry.terraform.io/modules/infrablocks/network-load-balancer/aws/2.1.0-rc.8) includes this change.

**Comment by ravindrasinghh** [comment]
Thank you @tobyclemson

**Pull request merged**
